[package]
edition = "2018"
name = "spire-api"
# When releasing to crates.io:
# - Update CHANGELOG.md.
# - Create a new tag
version = "0.1.0"
authors = ["Max Lambrecht <maxlambrecht@gmail.com>"]
description = "Rust library for the SPIRE APIs"
license = "Apache-2.0"
repository = "https://github.com/maxlambrecht/rust-spiffe"
documentation = "https://docs.rs/spire-api"
readme = "README.md"
categories = ["cryptography"]
keywords = ["SPIFFE", "SPIRE"]

[dependencies]
bytes = { version = "1", features = ["serde"] }
spiffe = { path = "../spiffe" }
tonic = { version = "0.9", default-features = false, features = ["prost", "codegen", "transport"]}
prost = { version = "0.11"}
prost-types = {version = "0.11"}
tokio = { "version" = "1", features = ["net", "test-util"]}
tokio-stream = "0.1"
tower = { version = "0.4", features = ["util"] }
thiserror = "1.0"
url = "2.2"
asn1 = { package = "simple_asn1", version = "0.6" }
x509-parser = "0.15"
pkcs8 = "0.10"
jsonwebtoken = "8.3"
jsonwebkey = { version = "0.3", features = ["jsonwebtoken", "jwt-convert"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
zeroize = { version = "1.6", features = ["zeroize_derive"] }
time = "0.3"

[dev-dependencies]

[build-dependencies]
tonic-build = { version = "0.9", default-features = false, features = ["prost"] }
prost-build = "0.11"
anyhow = "1.0.65"

[features]
integration-tests = []
