version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/spiffe" # Location of the Cargo.toml file for spiffe crate
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/spire-api" # Location of the Cargo.toml file for spire-api crate
    schedule:
      interval: "daily"
