[package]
edition = "2018"
name = "spiffe"
# When releasing to crates.io:
# - Update CHANGELOG.md.
# - Create a new tag
version = "0.2.1"
authors = ["Max Lambrecht <maxlambrecht@gmail.com>"]
description = "Rust client library implementation for SPIFFE"
license = "Apache-2.0"
repository = "https://github.com/maxlambrecht/rust-spiffe"
documentation = "https://docs.rs/spiffe"
readme = "README.md"
categories = ["cryptography"]
keywords = ["SPIFFE", "X509", "JWT"]

[dependencies]
protobuf = {version = "2.27", optional = true }
futures = "0.3"
thiserror = "1.0"
url = "2.2"
asn1 = { package = "simple_asn1", version = "0.6" }
x509-parser = "0.13"
pkcs8 = "0.8"
jsonwebtoken = "8.1"
jsonwebkey = { version = "0.3", features = ["jsonwebtoken", "jwt-convert"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
zeroize = { version = "1.4", features = ["zeroize_derive"] }
time = "0.3"

tonic = { version = "0.8", default-features = false, features = ["prost", "codegen", "transport"], optional = true }
prost = { version = "0.11" , optional = true }
prost-types = {version = "0.11.1", optional = true }
tokio = { "version" = "1", features = ["full", "test-util"], optional = true }
tokio-stream = { version = "0.1.12", features = ["net"] , optional = true }
tower = { version = "0.4.12", features = ["full"], optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
grpcio = { version = "0.9", default-features = false, features = ["protobuf-codec"], optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
grpcio = { version = "0.9", default-features = false, features = ["protobuf-codec", "use-bindgen"], optional = true  }


[dev-dependencies]
jsonwebkey = { version = "0.3", features = ["generate"] }

# used to verify in tests that the certificates bytes from the X.509 SVIDs and bundle authorities
# are parseable as OpenSSL X.509 certificates.
openssl = { version = "0.10", features = ["vendored"] }

[build-dependencies]
tonic-build = { version = "0.8", default-features = false, features = ["prost"] }
prost-build = "0.11"
anyhow = "1.0.65"

[features]
tonic = ["dep:tonic", "dep:prost", "dep:prost-types", "dep:tokio", "dep:tokio-stream", "dep:tower"]
grpcio = ["dep:grpcio", "dep:protobuf"]
default = ["grpcio"]